# Generated by Django 6.0.6 on 2026-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percent', models.PositiveIntegerField(help_text='درصد تخفیف، مثلا 10 برای 10%')),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'مشکی'), ('white', 'سفید'), ('red', 'قرمز'), ('blue', 'آبی'), ('gray', 'طوسی'), ('green', 'سبز'), ('multi', 'چندرنگ')], default='black', max_length=20),
        ),
    ]
